# Generated by Django 3.2.3 on 2021-08-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_alter_pet_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
